spring.application.name=logitrack

# Configurações do Banco de Dados PostgreSQL (Local)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/logitrack_pro}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:logitrack_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:logitrack_super_secure_pass_2026}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA/Hibernate
# Usa 'none' ou 'validate' porque o banco já é criado pelo script init.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
